<footer class="css-footer clearfix">
	<center>
		<table class="css-article" cellpadding="5" cellspacing="5" style="width:80%;border:1;text-align:center;" class="static_text02">
			<tbody>
				<tr class="even">
					<td style="border:0;text-align:left;">
						<strong>Simple Money Solutions</strong><br />
						<a href="lease.php">Lease</a><br />
						<a href="loan.php">Loan</a><br />
						<a href="trade_finance.php">Trade Finance</a>
					</td>
					<td style="border:0;text-align:justify;">
						<strong>Our Company</strong><br />
							<a href="about.php">Overview</a><br />
							<a href="history.php">History</a><br />
							<a href="sme.php">SME</a>
					</td>
					<td style="border:0;text-align:justify;">
						<strong>Our People</strong><br />
							<a href="team.php">Management Team</a><br />
							<a href="careers.php">Careers</a>
					</td>
					<td style="border:0;text-align:justify;">
						<strong>Media Centre</strong><br />
							<a href="news.php">News and Interactions</a><br />
							<a href="events.php">Company Events</a>
					</td>
					<td style="border:0;text-align:justify;">
						<strong>Others</strong><br />
							<a href="contact.php">Contact Us</a><br />
							<a href="faq.php">FAQ</a>				
					</td>
					<td style="width:15%;border:0;text-align:justify;">
						<strong>Connect with us</strong><br />
						<iframe src="//www.facebook.com/plugins/like.php?href=http%3A%2F%2Fwww.facebook.com%2Fabujaleasingcompany&amp;width&amp;layout=button_count&amp;action=like&amp;show_faces=true&amp;share=false&amp;height=21" scrolling="no" frameborder="0" style="width: 100%; border:none; overflow:hidden; height:21px;" allowTransparency="true"></iframe>
						<!--<iframe src="//www.facebook.com/plugins/follow.php?href=https%3A%2F%2Fwww.facebook.com%2Fabujaleasingcompany&amp;width&amp;height=80&amp;colorscheme=light&amp;layout=standard&amp;show_faces=false" scrolling="no" frameborder="0" style="border:none; overflow:hidden; height:25px;" allowTransparency="true"></iframe>-->
						<!--<script src="//platform.linkedin.com/in.js" type="text/javascript" type="IN/FollowCompany" data-id="Abuja Leasing Company Limited" data-counter="right"></script>-->
						<!--<script src="https://apis.google.com/js/plusone.js" type="text/javascript"></script><g:plusone></g:plusone>-->
						<!--<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>-->
						<a href="http://www.facebook.com/abujaleasingcompany" title="Like us on Facebook"><img width="21px" height="21px" alt="" src="images/icon-facebook.png"></a>&nbsp;
						<!--<a href="" title="Follow us on Twitter"><img width="21px" height="21px" alt="" class="css-lightbox" src="images/icon-twitter.png"></a>&nbsp;-->
						<a href="http://ng.linkedin.com/in/abujaleasingcompany" title="Follow us on LinkedIn"><img width="21px" height="21px" alt="" src="images/icon-linkedin.png"></a>&nbsp;
						<a href="mailto: info@abujaleasingcompany.com" title="Email us"><img width="21px" height="21px" alt="" src="images/icon-email.png"></a>						
					</td>
				</tr>
				<!--<tr class="even">
					<td style="border:0;text-align:right;" colspan="6">
						<a href="http://freehitcountercode.com/"><img border="0" src="http://www.freehitcountercode.com/counter.php?b=ffffff&r=000000&f=000000&unique=0&start=0" width="120" height="30" /></a><br /><span style="font-size: 5%;"><a href="http://freehitcountercode.com/">free website hit counter code</a></span>
						<img border="0" src="http://www.freehitcountercode.com/counter.php?b=ffffff&r=000000&f=000000&unique=0&start=0" width="120" height="30" />
					</td>					
				</tr>-->
			</tbody>
		</table>
	</center>
</footer>