<header class="css-header clearfix">
	<div class="css-shapes">
		<h1 class="css-headline" data-left="1.17%"><a href="index.php">Abuja Leasing Company Ltd.</a></h1>
		<h2 class="css-slogan" data-left="0.63%">Simple Money Solutions</h2>
		<div class="css-object1559787589" data-left="100%"></div>
		<div class="css-object1038546814" data-left="0%"></div>
		<div class="css-object1448325346" data-left="100%"></div>
	</div>
	<?php /**<div id="css-flash-area">
		<div id="css-flash-container">
			<object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" width="1536" height="384" id="css-flash-object">
				<param name="movie" value="images/flash.swf">
				<param name="quality" value="best">
				<param name="scale" value="exactfit">
				<param name="wmode" value="transparent">
				<param name="flashvars" value="color1=0xFFFFFF&amp;alpha1=.50&amp;framerate1=24&amp;loop=true&amp;wmode=transparent">
				<param name="swfliveconnect" value="true">
				<!--[if !IE]>-->
				<object type="application/x-shockwave-flash" data="images/flash.swf" width="1536" height="384">
					<param name="quality" value="best">
					<param name="scale" value="exactfit">
					<param name="wmode" value="transparent">
					<param name="flashvars" value="color1=0xFFFFFF&amp;alpha1=.50&amp;framerate1=24&amp;loop=true&amp;wmode=transparent">
					<param name="swfliveconnect" value="true">
				<!--<![endif]-->
					<div class="css-flash-alt"><a href="http://www.adobe.com/go/getflashplayer"><img src="http://www.adobe.com/images/shared/download_buttons/get_flash_player.gif" alt="Get Adobe Flash player"></a></div>
				<!--[if !IE]>-->
				</object>
				<!--<![endif]-->
			</object>
		</div>
	</div> */ ?>             
</header>