<style>
	.css-content .css-postcontent-0 .layout-item-0 { padding-right: 10px;padding-left: 10px;  }
	.css-content .css-postcontent-0 .layout-item-1 { margin-top: 3px;  }
	.css-content .css-postcontent-0 .layout-item-2 {  border-collapse: separate;  }
	.css-content .css-postcontent-0 .layout-item-3 { color: #000000; background: #534B37; padding-right: 10px;padding-left: 10px; vertical-align: middle;  }
	.ie7 .post .layout-cell {border:none !important; padding:0 !important; }
	.ie6 .post .layout-cell {border:none !important; padding:0 !important; }
	.css-slidecontainerslideslide101 {
		position: relative;
		width: 380px;
		height: 262px;
	}
	.css-slidecontainerslideslide101 .css-slide-item
	{

	}
	.css-slidecontainerslideslide101 .css-slide-item {
		-webkit-transition: 600ms ease-in-out opacity;
		-moz-transition: 600ms ease-in-out opacity;
		-ms-transition: 600ms ease-in-out opacity;
		-o-transition: 600ms ease-in-out opacity;
		transition: 600ms ease-in-out opacity;
		position: absolute;
		display: none;
		left: 0;
		top: 0;
		opacity: 0;
		width:  100%;
		height: 100%;
	}
	.css-slidecontainerslideslide101 .active, .css-slidecontainerslideslide101 .next, .css-slidecontainerslideslide101 .prev {
		display: block;
	}
	.css-slidecontainerslideslide101 .active {
		opacity: 1;
	}
	.css-slidecontainerslideslide101 .next, .css-slidecontainerslideslide101 .prev {
		width: 100%;
	}
	.css-slidecontainerslideslide101 .next.forward, .css-slidecontainerslideslide101 .prev.back {
		opacity: 1;
	}
	.css-slidecontainerslideslide101 .active.forward {
		opacity: 0;
	}
	.css-slidecontainerslideslide101 .active.back {
		opacity: 0;
	}
	.css-slideslideslide1010 {
		background-image:  url('images/slideslideslide1010.png');
		background-position:  0 0;
		background-repeat: no-repeat;
	}
	.css-slideslideslide1011 {
		background-image:  url('images/slideslideslide1011.png');
		background-position:  0 0;
		background-repeat: no-repeat;
	}
	.css-slideslideslide1012 {
		background-image:  url('images/slideslideslide1012.png');
		background-position:  0 0;
		background-repeat: no-repeat;
	}
	.css-slideslideslide1013 {
		background-image:  url('images/slideslideslide1013.png');
		background-position:  0 0;
		background-repeat: no-repeat;
	}
	.css-slideslideslide1014 {
		background-image:  url('images/slideslideslide1014.png');
		background-position:  0 0;
		background-repeat: no-repeat;
	}
	.css-slidenavigatorslideslide101 {
		display: inline-block;
		position: absolute;
		direction: ltr !important;
		top: 242px;
		left: 39.61%;
		z-index: 101;
		line-height: 0 !important;
		-webkit-background-origin: border !important;
		-moz-background-origin: border !important;
		background-origin: border-box !important;
		-webkit-box-sizing: border-box;
		-moz-box-sizing: border-box;
		box-sizing: border-box;
		text-align: center;
		white-space: nowrap;
	}
	.css-slidenavigatorslideslide101 {
		background: #A39775;background: transparent;background: transparent;background: transparent;background: transparent;background: transparent;background: transparent;-svg-background: transparent;
		-webkit-border-radius:10px;-moz-border-radius:10px;border-radius:10px;
		padding:7px;
	}
	.css-slidenavigatorslideslide101 > a {
		background: #5F563F;background: #5F563F;background: #5F563F;background: #5F563F;background: #5F563F;background: #5F563F;background: #5F563F;-svg-background: #5F563F;
		-webkit-border-radius:20%;-moz-border-radius:20%;border-radius:20%;
		margin:0 10px 0 0;
		width: 5px;
		height: 5px;
	}
	.css-slidenavigatorslideslide101 > a.active	{
		background: #50711E;background: #50711E;background: #50711E;background: #50711E;background: #50711E;background: #50711E;background: #50711E;-svg-background: #50711E;
		-webkit-border-radius:20%;-moz-border-radius:20%;border-radius:20%;
		border:1px solid #3C5516;
		margin:0 10px 0 0;
		width: 5px;
		height: 5px;
	}
	.css-slidenavigatorslideslide101 > a:hover {
		background: #50711E;background: #50711E;background: #50711E;background: #50711E;background: #50711E;background: #50711E;background: #50711E;-svg-background: #50711E;
		-webkit-border-radius:20%;-moz-border-radius:20%;border-radius:20%;
		border:1px solid #648D25;
		margin:0 10px 0 0;
		width: 5px;
		height: 5px;
	}
</style>