<?php include("sess.php"); include("conn.php");
	error_reporting(E_ALL ^ E_NOTICE ^ E_WARNING);
	include("a.inc"); ?>
	<h2 class="css-postheader">In the beginning...</h2>
		<blockquote>Abuja Leasing Company was modeled as a Public Private Partnership (PPP) to develop an integrated transportation network consistent with the Abuja Master Plan. The principal goal was to provide lease finance to operators who will provide an organized, modern and efficient taxi fleet befitting the status of Abuja as the nation's capital city.</blockquote>
		<blockquote>In line with this objective the Federal Capital Territory Administration (FCTA) through its investment and commercial arm -- The Abuja Investment Company Limited (AICL) established Abuja Leasing Company. Thus ALC's objective was to 'provide a structured, decent, organized, affordable and technologically driven transportation system tailored towards satisfying the needs of Abuja residents and visitors.</blockquote>
		<blockquote>Abuja Leasing Company Limited commenced business in the year 2005 with the initial share capital of &#8358;250 million which was later increased to &#8358;1.5 billion in 2007.</blockquote>
		<blockquote>The Company started with an initial fleet of 110 vehicles in 2005 (100 Peugeot 307 and 10 London Taxis TXII); aand has been expanded to 1,308 vehicles (1,000 Peugeot 307, 48 London Taxis and 260 Hyundai buses).</blockquote>
	<h2 class="css-postheader">...back in the days</h2>
		<blockquote>The operations of the Abuja Green Cabs Scheme were structured under a finance lease arrangement. The first 500 units of the 307 Peugeot vehicles were partly financed by Peugot Automobile of Nigeria (PAN) on a two-year credit facility while the company structured the lease facility with the respective operators on four-year tenure.</blockquote>
		<blockquote>The company in the year 2007 secured a credit facility from Ecobank Plc for the financing of additional 200 units of 307 Peugeot vehicles, which facility as at date has been discharged to about 83%.</blockquote>
		<blockquote>In the year 2008, the company, in achieving its fleet expansion project, secured another credit facility from Oceanic Bank for the financing of additional 300 units of the 307 Peugeot vehicles. This then brought the number of the Green Cabs to 1000 units. The company is gradually and progressively discharging its obligation to the banks. The operators of the Green Cabs made their equity contribution for the lease of the cabs.</blockquote>
		<blockquote>The company procured the initial 10 units of the Black Cabs in 2005, and an additional 38 units in 2006. The black cabs were known as FCT executive fleet. Forty-eight (48) units were deployed in hotels and the airport in Abuja. In addition, ALC financed the training of three of its technicians for an intensive training program in Coventry, United Kingdom. The technicians were trained in the repairs and servicing of the vehicles.<br /><br />The operations of the LTI vehicles were smooth and profitable for the first year, until the issues of the breakdown of the vehicles and the non-availability of the servicing parts became very challenging.</blockquote>
		<blockquote>The company initially made efforts to source from the manufacturers of the vehicles the servicing parts with little success. Due to the servicing parts problem the continuous breakdown of the vehicles reduced the number on the road which invariably affected the income level.</blockquote>
<?php include("z.inc"); ?>