<li><a href="home.php">Home</a></li>
<li><a href="">Simple Money Solutions</a><ul>
	<li><a href="lease.php">Lease</a></li>
	<li><a href="loan.php">Loan</a></li>
	<li><a href="trade_finance.php">Trade Finance</a></li>
</ul></li>
<li><a href="about.php">Our Company</a><ul>
	<li><a href="about.php">Overview</a></li>
	<li><a href="history.php">History</a></li>
	<li><a href="sme.php">Small Medium Enterprise</a></li>
</ul></li>
<li><a href="team.php">Our People</a><ul>
	<li><a href="team.php">Management Team</a></li>
	<li><a href="careers.php">Careers</a></li>
</ul></li>
<li><a href="events.php">Media Centre</a></li>
<li><a href="contact.php">More...</a><ul>
	<li><a href="contact.php">Contact Us</a></li>
	<li><a href="faq.php">FAQ</a></li>
</ul></li>