<div class="css-layout-cell css-sidebar2 clearfix">
	<!--<div class="css-block clearfix">
		<div class="css-blockheader"><h3 class="t">Contact Us</h3></div>
		<div class="css-blockcontent">
			<p><span style="font-size: 12px;text-decoration: underline;">ALC Hotline:</span><br />092918505</p>
			<br />
			<p><span style="font-size: 12px; text-decoration: underline;">ALC Office:</span><br />Foundation Plaza, Gr. Flr., Plot 792 Shettima Munguno Crescent, Utako, Abuja, Nigeria</p>
		</div>
	</div>-->	
	<div class="css-block clearfix">
		<div class="css-blockheader"><h3 class="t">Lease It</h3></div>
		<div class="css-blockcontent">
			<div id="8b2c34cc85e64992aaddd69bca68111a" style="position: relative; display: inline-block; z-index: 0; margin: 5px;  border-width: 0px; width: auto; height: auto;  float: left;" class="css-collage">
				<div class="css-slider css-slidecontainer8b2c34cc85e64992aaddd69bca68111a">
					<div class="css-slider-inner">
						<div class="css-slide-item css-slide8b2c34cc85e64992aaddd69bca68111a0"></div>
						<div class="css-slide-item css-slide8b2c34cc85e64992aaddd69bca68111a1"></div>
						<div class="css-slide-item css-slide8b2c34cc85e64992aaddd69bca68111a2"></div>
						<div class="css-slide-item css-slide8b2c34cc85e64992aaddd69bca68111a3"></div>
						<div class="css-slide-item css-slide8b2c34cc85e64992aaddd69bca68111a4"></div>
						<div class="css-slide-item css-slide8b2c34cc85e64992aaddd69bca68111a5"></div>
						<div class="css-slide-item css-slide8b2c34cc85e64992aaddd69bca68111a6"></div>
						<div class="css-slide-item css-slide8b2c34cc85e64992aaddd69bca68111a7"></div>
						<div class="css-slide-item css-slide8b2c34cc85e64992aaddd69bca68111a8"></div>
						<div class="css-slide-item css-slide8b2c34cc85e64992aaddd69bca68111a9"></div>
						<div class="css-slide-item css-slide8b2c34cc85e64992aaddd69bca68111a10"></div>
						<div class="css-slide-item css-slide8b2c34cc85e64992aaddd69bca68111a11"></div>
					</div>
				</div>
				<!--<div class="css-slidenavigator css-slidenavigator8b2c34cc85e64992aaddd69bca68111a">
					<a href="#" class="css-slidenavigatoritem"></a>
					<a href="#" class="css-slidenavigatoritem"></a>
					<a href="#" class="css-slidenavigatoritem"></a>
					<a href="#" class="css-slidenavigatoritem"></a>
					<a href="#" class="css-slidenavigatoritem"></a>
					<a href="#" class="css-slidenavigatoritem"></a>
					<a href="#" class="css-slidenavigatoritem"></a>
					<a href="#" class="css-slidenavigatoritem"></a>
					<a href="#" class="css-slidenavigatoritem"></a>
					<a href="#" class="css-slidenavigatoritem"></a>
					<a href="#" class="css-slidenavigatoritem"></a>
					<a href="#" class="css-slidenavigatoritem"></a>
				</div>-->
			</div>
		</div>
	</div>
	<div class="css-block clearfix">
        <div class="css-blockheader"><h3 class="t">Leasing Process</h3></div>
        <div class="css-blockcontent">
			<p style="text-align:center;"><img width="175" height="140" alt="" class="css-lightbox" src="images/individual-2.png"></p>
		</div>
	</div>
	<div class="css-block clearfix">
		<div class="css-blockheader"><h3 class="t">Download Forms</h3></div>
		<div class="css-blockcontent"><p> </p>
			<ul>
				<li><a href="files/profile.pdf" style="text-decoration:none;">Company Profile</a></li>
				<li><a href="files/lease_requirements.pdf" style="text-decoration:none;">Lease Requirements</a></li>
				<li><a href="files/trade_finance_requirements.pdf" style="text-decoration:none;">Trade Finance Req.</a></li>
				<li><a href="files/lease_individual.pdf" style="text-decoration:none;">Lease App (Ind.)</a></li>
				<li><a href="files/lease_corporate.pdf" style="text-decoration:none;">Lease App (Corp.)</a></li>
				<li><a href="files/trade_finance_individual.pdf" style="text-decoration:none;">Trade Fin. App (Ind.)</a></li>
				<li><a href="files/trade_finance_corporate.pdf" style="text-decoration:none;">Trade Fin. App (Corp.)</a></li>
				<li><a href="files/kyc_form.pdf" style="text-decoration:none;">KYC Form</a></li>
				<li><a href="files/guarantor_form.pdf" style="text-decoration:none;">Guarantor's Form</a></li>
			</ul>
		</div>
	</div>
	<div class="css-block clearfix">
		<div class="css-blockheader"><h3 class="t">Login</h3></div>
		<div class="css-blockcontent">
			<form method="POST" action="<?php echo htmlspecialchars("login.php");?>" target="_self" enctype="multipart/form-data">
				<label for="username">Username:<br /><input type="text" id="username" name="username" title="Username" autocomplete="off" />
				<label for="password">Password:<br /><input type="password" id="password" name="password" title="Usercode" />
				<br /><br />
				<!--<p style="text-align:right;">-->
					<input type="submit" id="login" name="login" class="css-button css-button" value="Login" />
					<input type="submit" id="clear" name="clear" class="css-button css-button" value="Clear" />
				<!--</p>-->
			</form>
		</div>
	</div>	
</div>