<style>
	.css-slidecontainer8b2c34cc85e64992aaddd69bca68111a {
		position: relative;
			width: 170px;
		height: 114px;
	}
	.css-slidecontainer8b2c34cc85e64992aaddd69bca68111a .css-slide-item
	{

	}
	.css-slidecontainer8b2c34cc85e64992aaddd69bca68111a .css-slide-item {
		-webkit-transition: 600ms ease-in-out opacity;
		-moz-transition: 600ms ease-in-out opacity;
		-ms-transition: 600ms ease-in-out opacity;
		-o-transition: 600ms ease-in-out opacity;
		transition: 600ms ease-in-out opacity;
		position: absolute;
		display: none;
		left: 0;
		top: 0;
		opacity: 0;
		width:  100%;
		height: 100%;
	}
	.css-slidecontainer8b2c34cc85e64992aaddd69bca68111a .active, .css-slidecontainer8b2c34cc85e64992aaddd69bca68111a .next, .css-slidecontainer8b2c34cc85e64992aaddd69bca68111a .prev {
		display: block;
	}
	.css-slidecontainer8b2c34cc85e64992aaddd69bca68111a .active {
		opacity: 1;
	}
	.css-slidecontainer8b2c34cc85e64992aaddd69bca68111a .next, .css-slidecontainer8b2c34cc85e64992aaddd69bca68111a .prev {
		width: 100%;
	}
	.css-slidecontainer8b2c34cc85e64992aaddd69bca68111a .next.forward, .css-slidecontainer8b2c34cc85e64992aaddd69bca68111a .prev.back {
		opacity: 1;
	}
	.css-slidecontainer8b2c34cc85e64992aaddd69bca68111a .active.forward {
		opacity: 0;
	}
	.css-slidecontainer8b2c34cc85e64992aaddd69bca68111a .active.back {
		opacity: 0;
	}
	.css-slide8b2c34cc85e64992aaddd69bca68111a0 {
		background-image:  url('images/slide8b2c34cc85e64992aaddd69bca68111a0.png');
		background-position:  0 0;
		background-repeat: no-repeat;
	}
	.css-slide8b2c34cc85e64992aaddd69bca68111a1 {
		background-image:  url('images/slide8b2c34cc85e64992aaddd69bca68111a1.png');
		background-position:  0 0;
		background-repeat: no-repeat;
	}
	.css-slide8b2c34cc85e64992aaddd69bca68111a2 {
		background-image:  url('images/slide8b2c34cc85e64992aaddd69bca68111a2.png');
		background-position:  0 0;
		background-repeat: no-repeat;
	}
	.css-slide8b2c34cc85e64992aaddd69bca68111a3 {
		background-image:  url('images/slide8b2c34cc85e64992aaddd69bca68111a3.png');
		background-position:  0 0;
		background-repeat: no-repeat;
	}
	.css-slide8b2c34cc85e64992aaddd69bca68111a4 {
		background-image:  url('images/slide8b2c34cc85e64992aaddd69bca68111a4.png');
		background-position:  0 0;
		background-repeat: no-repeat;
	}
	.css-slide8b2c34cc85e64992aaddd69bca68111a5 {
		background-image:  url('images/slide8b2c34cc85e64992aaddd69bca68111a5.png');
		background-position:  0 0;
		background-repeat: no-repeat;
	}
	.css-slide8b2c34cc85e64992aaddd69bca68111a6 {
		background-image:  url('images/slide8b2c34cc85e64992aaddd69bca68111a6.png');
		background-position:  0 0;
		background-repeat: no-repeat;
	}
	.css-slide8b2c34cc85e64992aaddd69bca68111a7 {
		background-image:  url('images/slide8b2c34cc85e64992aaddd69bca68111a7.png');
		background-position:  0 0;
		background-repeat: no-repeat;
	}
	.css-slide8b2c34cc85e64992aaddd69bca68111a8 {
		background-image:  url('images/slide8b2c34cc85e64992aaddd69bca68111a8.png');
		background-position:  0 0;
		background-repeat: no-repeat;
	}
	.css-slide8b2c34cc85e64992aaddd69bca68111a9 {
		background-image:  url('images/slide8b2c34cc85e64992aaddd69bca68111a9.png');
		background-position:  0 0;
		background-repeat: no-repeat;
	}
	.css-slide8b2c34cc85e64992aaddd69bca68111a10 {
		background-image:  url('images/slide8b2c34cc85e64992aaddd69bca68111a10.png');
		background-position:  0 0;
		background-repeat: no-repeat;
	}
	.css-slide8b2c34cc85e64992aaddd69bca68111a11 {
		background-image:  url('images/slide8b2c34cc85e64992aaddd69bca68111a11.png');
		background-position:  0 0;
		background-repeat: no-repeat;
	}
	.css-slidenavigator8b2c34cc85e64992aaddd69bca68111a {
		display: inline-block;
		position: absolute;
		direction: ltr !important;
		top: 95px;
		left: 12.06%;
		z-index: 101;
		line-height: 0 !important;
		-webkit-background-origin: border !important;
		-moz-background-origin: border !important;
		background-origin: border-box !important;
		-webkit-box-sizing: border-box;
		-moz-box-sizing: border-box;
		box-sizing: border-box;
		text-align: center;
		white-space: nowrap;
	}
	.css-slidenavigator8b2c34cc85e64992aaddd69bca68111a	{
		background: #A39775;background: transparent;background: transparent;background: transparent;background: transparent;background: transparent;background: transparent;-svg-background: transparent;
		padding:7px;
	}
	.css-slidenavigator8b2c34cc85e64992aaddd69bca68111a > a {
		background: #5F563F;background: #5F563F;background: #5F563F;background: #5F563F;background: #5F563F;background: #5F563F;background: #5F563F;-svg-background: #5F563F;
		-webkit-border-radius:20%;-moz-border-radius:20%;border-radius:20%;
		margin:0 5px 0 0;
		width: 5px;
		height: 5px;
	}
	.css-slidenavigator8b2c34cc85e64992aaddd69bca68111a > a.active {
		background: #50711E;background: #50711E;background: #50711E;background: #50711E;background: #50711E;background: #50711E;background: #50711E;-svg-background: #50711E;
		-webkit-border-radius:20%;-moz-border-radius:20%;border-radius:20%;
		border:1px solid #3C5516;
		margin:0 5px 0 0;
		width: 5px;
		height: 5px;
	}
	.css-slidenavigator8b2c34cc85e64992aaddd69bca68111a > a:hover {
		background: #50711E;background: #50711E;background: #50711E;background: #50711E;background: #50711E;background: #50711E;background: #50711E;-svg-background: #50711E;
		-webkit-border-radius:20%;-moz-border-radius:20%;border-radius:20%;
		border:1px solid #648D25;
		margin:0 5px 0 0;
		width: 5px;
		height: 5px;
	}
	</style>